# Generated by Django 4.1 on 2023-01-24 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projects.models.projects


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Development_Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tasks_ppo",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="Задания на ППО"
                    ),
                ),
                (
                    "name_systems",
                    models.CharField(max_length=250, verbose_name="Название системы"),
                ),
                (
                    "status_systems",
                    models.CharField(
                        choices=[
                            ("New_Object", "Новый объект"),
                            ("Overhaul", "Капитальный ремонт"),
                            ("Reconstruction", "Реконструкция"),
                        ],
                        default="New_Object",
                        max_length=50,
                        verbose_name="Статус системы",
                    ),
                ),
                ("task", models.TextField(verbose_name="Описание задания")),
                (
                    "part_equipment",
                    models.TextField(verbose_name="Состав оборудования"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Done", "Выполнено"),
                            ("Not_done", "Не выполнено"),
                            ("Running", "Выполняется"),
                            ("Suspended", "Приостановлено"),
                        ],
                        default="Not_done",
                        max_length=50,
                        verbose_name="Отметка выполнения",
                    ),
                ),
                (
                    "date_software_development_planned",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Разработка ППО. Планируемая.",
                    ),
                ),
                (
                    "date_software_development_actual",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Разработка ППО. Фактическая.",
                    ),
                ),
                (
                    "date_documentation_development_planned",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Разработка документации. Планируемая.",
                    ),
                ),
                (
                    "date_documentation_development_actual",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Разработка документации. Фактическая.",
                    ),
                ),
                (
                    "date_factory_acceptance_planned",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Заводская приемка. Планируемая.",
                    ),
                ),
                (
                    "date_factory_acceptance_actual",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Заводская приемка. Фактическая.",
                    ),
                ),
                (
                    "date_shipment_equipment_planned",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Отгрузка оборудования. Планируемая.",
                    ),
                ),
                (
                    "date_shipment_equipment_actual",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Отгрузка оборудования. Фактическая.",
                    ),
                ),
                (
                    "source_data_folder",
                    models.CharField(
                        max_length=255, verbose_name="Папка с исходными данными"
                    ),
                ),
                (
                    "date_issue",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата регистрации задания.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Задание на разработку",
                "verbose_name_plural": "Задание на разработки",
                "ordering": ["date_issue"],
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Objects_Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Позиция"
                    ),
                ),
                (
                    "short_names",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        unique=True,
                        verbose_name="Обиходные название",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание позиции"),
                ),
                (
                    "сabinet_inspection_form",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.projects.сabinet_inspection_form_path_files,
                        verbose_name="Бланк проверки шкафа",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Factory_acceptance", "Заводская приемка"),
                            ("Waiting_for_setup", "Ожидание наладки"),
                            ("Commissioning", "Пусконаладочные работы"),
                            ("Experimental_exploitation", "Опытная эксплатация"),
                            ("Completed_project", "Законченный проект"),
                        ],
                        default="Factory_acceptance",
                        max_length=50,
                        verbose_name="Состояние проекта",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Позиция",
                "verbose_name_plural": "Позиции",
                "ordering": ["pk"],
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Objects_Position_Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание документа"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.projects.objects_position_path_files,
                        verbose_name="Документ",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Позиция. Документ",
                "verbose_name_plural": "Позиция. Документы",
                "ordering": ["date_joined"],
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Фирма"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("customer", "Заказчик"),
                            ("exploitation", "Эксплуатация"),
                            ("designer", "Проектировщик"),
                        ],
                        default="customer",
                        max_length=50,
                        verbose_name="Направление фирмы",
                    ),
                ),
                (
                    "site",
                    models.URLField(blank=True, max_length=255, verbose_name="Сайт"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание фирмы"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Фирма",
                "verbose_name_plural": "Фирмы",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Organizations_Objects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название объекта"
                    ),
                ),
                (
                    "name_tables",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Название для табеля"
                    ),
                ),
                (
                    "short_names",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        unique=True,
                        verbose_name="Обиходные название",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание объекта"),
                ),
                (
                    "property_location",
                    models.TextField(
                        blank=True, verbose_name="Расположение объекта. Транспорт."
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Organizations_Objects_Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание документа"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.projects.objects_directory_path_files,
                        verbose_name="Документ",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Объект. Документ",
                "verbose_name_plural": "Объект. Документы",
                "ordering": ["date_joined"],
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Status_Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "сurrent_state",
                    models.CharField(
                        choices=[
                            ("Done", "Отсутсвует"),
                            ("Factory tested", "Заводская испытания"),
                            ("Waiting adjustment", "Ожидание наладки"),
                            ("Commissioning works", "Пусконаладочные работы"),
                            (
                                "Waiting trial operation",
                                "Ожидание опытной эксплуатация",
                            ),
                            ("Trial operation", "Опытная эксплуатация"),
                            ("Completed projects", "Законченный проект"),
                        ],
                        default="Not_done",
                        max_length=50,
                        verbose_name="Статус проекта",
                    ),
                ),
                (
                    "status_factory_tested",
                    models.CharField(
                        choices=[
                            ("Done", "Выполнено"),
                            ("Not_done", "Не выполнено"),
                            ("Running", "Выполняется"),
                            ("Suspended", "Приостановлено"),
                        ],
                        default="Not_done",
                        max_length=50,
                        verbose_name="Заводская испытания",
                    ),
                ),
                (
                    "status_commissioning_works",
                    models.CharField(
                        choices=[
                            ("Done", "Выполнено"),
                            ("Not_done", "Не выполнено"),
                            ("Running", "Выполняется"),
                            ("Suspended", "Приостановлено"),
                        ],
                        default="Not_done",
                        max_length=50,
                        verbose_name="Пусконаладочные работы",
                    ),
                ),
                (
                    "status_trial_operation",
                    models.CharField(
                        choices=[
                            ("Done", "Выполнено"),
                            ("Not_done", "Не выполнено"),
                            ("Running", "Выполняется"),
                            ("Suspended", "Приостановлено"),
                        ],
                        default="Not_done",
                        max_length=50,
                        verbose_name="Опытная эксплуатация",
                    ),
                ),
                (
                    "status_completed_projects",
                    models.CharField(
                        choices=[
                            ("Done", "Выполнено"),
                            ("Not_done", "Не выполнено"),
                            ("Running", "Выполняется"),
                            ("Suspended", "Приостановлено"),
                        ],
                        default="Not_done",
                        max_length=50,
                        verbose_name="Законченные проекты",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название документа"
                    ),
                ),
                (
                    "cipher",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Шифр документа"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание документа"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Название документа",
                "verbose_name_plural": "Название документов",
                "ordering": ["pk"],
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Produced_Сabinets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "factory_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Заводской номер"
                    ),
                ),
                ("сomments", models.TextField(blank=True, verbose_name="Коментарии")),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="URL"),
                ),
                (
                    "objects_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.objects_position",
                        verbose_name="Позиция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шкаф",
                "verbose_name_plural": "Шкафы",
                "ordering": ["factory_number"],
                "default_permissions": "",
            },
        ),
    ]
