# Generated by Django 4.1 on 2023-01-10 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workers", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produced_сabinets",
            name="сabinet_builder",
            field=models.ManyToManyField(
                blank=True,
                related_name="user2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сборщик",
            ),
        ),
        migrations.AddField(
            model_name="produced_сabinets",
            name="сabinet_сonstructor",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user1",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Конструктор",
            ),
        ),
        migrations.AddField(
            model_name="organizations_objects_documents",
            name="organizations_objects",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.organizations_objects",
                verbose_name="Название объекта",
            ),
        ),
        migrations.AddField(
            model_name="organizations_objects_documents",
            name="type_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.type_document",
                verbose_name="Тип документа",
            ),
        ),
        migrations.AddField(
            model_name="organizations_objects",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.organization",
                verbose_name="Эксплуатирующая фирма",
            ),
        ),
        migrations.AddField(
            model_name="objects_position_documents",
            name="objects_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.objects_position",
                verbose_name="Позиция",
            ),
        ),
        migrations.AddField(
            model_name="objects_position_documents",
            name="type_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.type_document",
                verbose_name="Тип документа",
            ),
        ),
        migrations.AddField(
            model_name="objects_position",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workers.department",
                verbose_name="Задание на отделе",
            ),
        ),
        migrations.AddField(
            model_name="objects_position",
            name="organizations_objects",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.organizations_objects",
                verbose_name="Название объекта",
            ),
        ),
        migrations.AddField(
            model_name="objects_position",
            name="subdivision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workers.subdivision",
                verbose_name="Задание на управлении",
            ),
        ),
        migrations.AddField(
            model_name="objects_position",
            name="сhecking_cabinet",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Проверяющие шкаф"
            ),
        ),
        migrations.AddField(
            model_name="development_task",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization1",
                to="projects.organization",
                verbose_name="Заказчик",
            ),
        ),
        migrations.AddField(
            model_name="development_task",
            name="designer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization3",
                to="projects.organization",
                verbose_name="Проектировщик",
            ),
        ),
        migrations.AddField(
            model_name="development_task",
            name="exploitation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization2",
                to="projects.organization",
                verbose_name="Эксплуатация",
            ),
        ),
        migrations.AddField(
            model_name="development_task",
            name="gip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ф.И.О. ГИПа",
            ),
        ),
        migrations.AddField(
            model_name="development_task",
            name="objects_position",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.objects_position",
                verbose_name="Позиция",
            ),
        ),
        migrations.AddField(
            model_name="development_task",
            name="organizations_objects",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.organizations_objects",
                verbose_name="Объект",
            ),
        ),
    ]
