# Generated by Django 4.1 on 2023-01-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата/время изменения"
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=255, null=True, verbose_name="Таблица"),
                ),
                ("record_id", models.IntegerField(null=True, verbose_name="ID записи")),
                (
                    "action_on_model",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("update", "Изменение"),
                            ("delete", "Удаление"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, verbose_name="Изменяемые данные модели"
                    ),
                ),
                (
                    "ipaddress",
                    models.CharField(
                        max_length=15, null=True, verbose_name="IP адресс"
                    ),
                ),
            ],
            options={
                "verbose_name": "Change log",
                "verbose_name_plural": "Change logs",
                "ordering": ("changed",),
            },
        ),
    ]
