# Generated by Django 4.1 on 2023-01-24 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workers_certificates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Сertificate_Parts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название части"
                    ),
                ),
                (
                    "validity",
                    models.IntegerField(
                        default=0, verbose_name="Срок годности месяцев"
                    ),
                ),
                (
                    "change_chief",
                    models.BooleanField(
                        default=False,
                        verbose_name="Не актуальность при смене должности",
                    ),
                ),
                (
                    "state",
                    models.BooleanField(default=True, verbose_name="Актуальность"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Сертификат части",
                "verbose_name_plural": "Сертификаты части",
                "ordering": ["pk"],
                "permissions": (
                    ("certificate_parts_view", "Сертификаты части. Просмотр."),
                    ("certificate_parts_change", "Сертификаты части. Редактирование."),
                    ("certificate_parts_delete", "Сертификаты части. Удаление."),
                    ("certificate_parts_add", "Сертификаты части. Добавить."),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Сertificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название сертификата"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "how_to_take",
                    models.TextField(null=True, verbose_name="Как сдавать"),
                ),
                ("answers", models.TextField(null=True, verbose_name="Ответы")),
                (
                    "state",
                    models.BooleanField(default=True, verbose_name="Актуальность"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
                "ordering": ["pk"],
                "permissions": (
                    ("certificates_view", "Сертификаты. Просмотр."),
                    ("certificates_change", "Сертификаты. Редактирование."),
                    ("certificates_delete", "Сертификаты. Удаление."),
                    ("certificates_add", "Сертификаты. Добавить."),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Сertificate_Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_delivery",
                    models.DateField(
                        blank=True, verbose_name="Дата начала действия сертификата"
                    ),
                ),
                (
                    "file1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers_certificates.models.user_directory_certificate1,
                        verbose_name="Скан №1",
                    ),
                ),
                (
                    "file2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers_certificates.models.user_directory_certificate2,
                        verbose_name="Скан №2",
                    ),
                ),
                (
                    "file3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers_certificates.models.user_directory_certificate3,
                        verbose_name="Скан №3",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workers_certificates.сertificate_parts",
                        verbose_name="Сертификаты часть",
                    ),
                ),
                (
                    "chief",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workers.chief",
                        verbose_name="Должность",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ФИО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат работника",
                "verbose_name_plural": "Сертификаты работников",
                "ordering": ["pk"],
                "permissions": (
                    ("certificate_users_view", "Сертификаты сотрудников. Просмотр."),
                    (
                        "certificate_users_change",
                        "Сертификаты сотрудников. Редактирование.",
                    ),
                    ("certificate_users_delete", "Сертификаты сотрудников. Удаление."),
                    ("certificate_users_add", "Сертификаты сотрудников. Добавить."),
                    (
                        "certificate_users_change_superiors",
                        "Сертификаты сотрудников. Редактирование. Руководство.",
                    ),
                    (
                        "certificate_users_delete_superiors",
                        "Сертификаты сотрудников. Удаление. Руководство.",
                    ),
                    (
                        "certificate_users_add_superiors",
                        "Сертификаты сотрудников. Добавить. Руководство.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.AddField(
            model_name="сertificate_parts",
            name="certificates",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workers_certificates.сertificates",
                verbose_name="Сертификаты",
            ),
        ),
    ]
