# Generated by Django 4.1 on 2023-01-10 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import workers.models.certificate
import workers.models.workers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("surname", models.CharField(max_length=60, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=60, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=60, verbose_name="Отчество"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "employee",
                    models.CharField(
                        choices=[("employee", "Сотрудник"), ("fired", "Уволен")],
                        default="employee",
                        max_length=30,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "employee_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.workers.workers_image_path,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "image_smol",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.workers.workers_image_path,
                        verbose_name="Фото",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["chief"],
                "permissions": (
                    ("workers_view", "Просмотр страницы пользователя."),
                    ("workers_change_image", "Редактировать фотографию."),
                    ("workers_change_contact", "Редактировать контакты."),
                    (
                        "workers_view_superiors",
                        "Просмотр страницы пользователя. Руководство.",
                    ),
                    (
                        "workers_update_password_superiors",
                        "Обновление пароля. Руководство.",
                    ),
                    ("workers_add_superiors", "Добавить пользователя. Руководство."),
                    (
                        "workers_change_image_superiors",
                        "Редактировать фотографию. Руководство.",
                    ),
                    (
                        "workers_change_contact_superiors",
                        "Редактировать контакты. Руководство.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Chief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Должность"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "rights",
                    models.IntegerField(
                        default=0, unique=True, verbose_name="Уровень доступа"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth.group",
                        verbose_name="Группы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Структура. Должность",
                "verbose_name_plural": "Структура. Должности",
                "ordering": ["rights"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Отдел"),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Структура. Отдел",
                "verbose_name_plural": "Структура. Отделы",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Subdivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Управление/Подразделение",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Структура. Управление",
                "verbose_name_plural": "Структура. Управления",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Сertificate_Parts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название части"
                    ),
                ),
                ("years", models.IntegerField(default=0, verbose_name="Срок годности")),
                (
                    "change_chief",
                    models.BooleanField(
                        default=False,
                        verbose_name="Не актуальность при смене должности",
                    ),
                ),
                (
                    "state",
                    models.BooleanField(default=True, verbose_name="Актуальность"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Сертификат части",
                "verbose_name_plural": "Сертификаты части",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Сertificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название сертификата"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "how_to_take",
                    models.TextField(null=True, verbose_name="Как сдавать"),
                ),
                ("answers", models.TextField(null=True, verbose_name="Ответы")),
                (
                    "state",
                    models.BooleanField(default=True, verbose_name="Актуальность"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Сertificate_Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_delivery",
                    models.DateField(
                        blank=True, verbose_name="Дата начала действия сертификата"
                    ),
                ),
                (
                    "file1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.certificate.user_directory_certificate1,
                        verbose_name="Скан №1",
                    ),
                ),
                (
                    "file2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.certificate.user_directory_certificate2,
                        verbose_name="Скан №2",
                    ),
                ),
                (
                    "file3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.certificate.user_directory_certificate3,
                        verbose_name="Скан №3",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workers.сertificate_parts",
                        verbose_name="Сертификаты часть",
                    ),
                ),
                (
                    "chief",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workers.chief",
                        verbose_name="Должность",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ФИО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат работника",
                "verbose_name_plural": "Сертификаты работников",
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="сertificate_parts",
            name="certificates",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workers.сertificates",
                verbose_name="Сертификаты",
            ),
        ),
        migrations.CreateModel(
            name="User_Closed_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_order_of_employment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Приказ о трудоустройстве",
                    ),
                ),
                (
                    "organization_labor_contract",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Трудовой договор",
                    ),
                ),
                (
                    "passport_serial",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Паспорт Серия"
                    ),
                ),
                (
                    "passport_number",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Паспорт Номер"
                    ),
                ),
                (
                    "passport_passport_issued",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Паспорт Выдан",
                    ),
                ),
                (
                    "passport_passport_issued_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Паспорт Дата выдачи"
                    ),
                ),
                (
                    "passport_place_of_issue",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Паспорт Код подразделения",
                    ),
                ),
                (
                    "passport_registration",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Паспорт Место выдачи",
                    ),
                ),
                (
                    "passport_of_residence",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Паспорт Место жительства",
                    ),
                ),
                (
                    "passport_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.workers.user_directory_path_save,
                        verbose_name="Паспорт скан",
                    ),
                ),
                (
                    "snils_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="СНИЛС номер",
                    ),
                ),
                (
                    "snils_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.workers.user_directory_path_save,
                        verbose_name="СНИЛС скан",
                    ),
                ),
                (
                    "inn_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Инн номер"
                    ),
                ),
                (
                    "inn_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.workers.user_directory_path_save,
                        verbose_name="Инн скан",
                    ),
                ),
                (
                    "archive_documents_employment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.workers.user_directory_path_save,
                        verbose_name="Пакет документов при трудоустройстве",
                    ),
                ),
                (
                    "signature_example",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=workers.models.workers.user_directory_path_files,
                        verbose_name="Пример подписи",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ФИО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудники закрытая информация",
                "verbose_name_plural": "Сотрудники закрытая информация",
                "ordering": ["pk"],
                "permissions": (
                    ("user_basic_views", "Закрытая инфомрация. Просмотр."),
                    (
                        "user_basic_add_passport_superiors",
                        "Закрытая инфомрация. Редактирование. Паспорт. Руководство.",
                    ),
                    (
                        "user_basic_views_passport_superiors",
                        "Закрытая инфомрация. Просмотр. Паспорт. Руководство.",
                    ),
                    (
                        "user_basic_add_snils_superiors",
                        "Закрытая инфомрация. Редактирование. СНИЛС. Руководство.",
                    ),
                    (
                        "user_basic_views_snils_superiors",
                        "Закрытая инфомрация. Просмотр. СНИЛС. Руководство.",
                    ),
                    (
                        "user_basic_add_inn_superiors",
                        "Закрытая инфомрация. Редактирование. ИНН. Руководство.",
                    ),
                    (
                        "user_basic_views_inn_superiors",
                        "Закрытая инфомрация. Просмотр. ИНН. Руководство.",
                    ),
                    (
                        "user_basic_add_signature_superiors",
                        "Закрытая инфомрация. Редактирование. Подпись. Руководство.",
                    ),
                    (
                        "user_basic_views_signature_superiors",
                        "Закрытая инфомрация. Просмотр. Подпись. Руководство.",
                    ),
                    (
                        "user_basic_views_superiors",
                        "Закрытая инфомрация. Просмотр. Руководство.",
                    ),
                    (
                        "user_basic_change_superiors",
                        "Закрытая инфомрация. Изменение. Руководство. Руководство.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="User_Basic_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_employment",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата трудоустройства"
                    ),
                ),
                (
                    "date_chief",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата в должности"
                    ),
                ),
                (
                    "number_ga",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Номер табеля"
                    ),
                ),
                (
                    "date_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "email_home",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Личная почта",
                    ),
                ),
                (
                    "phone_additional1",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="Телефон дополнительный №1",
                    ),
                ),
                (
                    "phone_additional2",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="Телефон дополнительный №2",
                    ),
                ),
                (
                    "home_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Домашний адрес",
                    ),
                ),
                (
                    "home_metro",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ближайшее метро",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Мужской"), ("Female", "Женский")],
                        max_length=10,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "department_in_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workers.department",
                        verbose_name="Отдел официально",
                    ),
                ),
                (
                    "subdivision_in_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workers.subdivision",
                        verbose_name="Управление официально",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ФИО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудники общая информация",
                "verbose_name_plural": "Сотрудники общая информация",
                "ordering": ["pk"],
                "permissions": (
                    ("user_basic_change", "Базовая информация. Изменение."),
                    ("user_basic_views", "Базовая информация. Просмотр."),
                    (
                        "user_basic_change_superiors",
                        "Базовая информация. Изменение. Руководство.",
                    ),
                    (
                        "user_basic_views_superiors",
                        "Базовая информация. Просмотр.Руководство.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="chief",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workers.chief",
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workers.department",
                verbose_name="Отдел фактически",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subdivision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workers.subdivision",
                verbose_name="Управление фактически",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
