# Generated by Django 4.1 on 2023-01-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user_closed_information",
            options={
                "default_permissions": "",
                "ordering": ["pk"],
                "permissions": (
                    ("user_basic_views", "Закрытая инфомрация. Просмотр."),
                    (
                        "user_basic_add_passport_superiors",
                        "Закрытая инфомрация. Редактирование. Паспорт. Руководство.",
                    ),
                    (
                        "user_basic_views_passport_superiors",
                        "Закрытая инфомрация. Просмотр. Паспорт. Руководство.",
                    ),
                    (
                        "user_basic_add_snils_superiors",
                        "Закрытая инфомрация. Редактирование. СНИЛС. Руководство.",
                    ),
                    (
                        "user_basic_views_snils_superiors",
                        "Закрытая инфомрация. Просмотр. СНИЛС. Руководство.",
                    ),
                    (
                        "user_basic_add_inn_superiors",
                        "Закрытая инфомрация. Редактирование. ИНН. Руководство.",
                    ),
                    (
                        "user_basic_views_inn_superiors",
                        "Закрытая инфомрация. Просмотр. ИНН. Руководство.",
                    ),
                    (
                        "user_basic_add_signature_superiors",
                        "Закрытая инфомрация. Редактирование. Подпись. Руководство.",
                    ),
                    (
                        "user_basic_views_signature_superiors",
                        "Закрытая инфомрация. Просмотр. Подпись. Руководство.",
                    ),
                    (
                        "user_basic_add_archive_superiors",
                        "Закрытая инфомрация. Редактирование. Архив при трудоустройстве. Руководство.",
                    ),
                    (
                        "user_basic_views_archive_superiors",
                        "Закрытая инфомрация. Просмотр. Архив при трудоустройстве. Руководство.",
                    ),
                    (
                        "user_basic_views_superiors",
                        "Закрытая инфомрация. Просмотр. Руководство.",
                    ),
                    (
                        "user_basic_change_superiors",
                        "Закрытая инфомрация. Изменение. Руководство. Руководство.",
                    ),
                ),
                "verbose_name": "Сотрудники закрытая информация",
                "verbose_name_plural": "Сотрудники закрытая информация",
            },
        ),
    ]
