# Generated by Django 4.1 on 2023-01-12 06:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0002_alter_user_closed_information_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_basic_information",
            name="email_home",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Личная почта"
            ),
        ),
        migrations.AlterField(
            model_name="user_basic_information",
            name="phone_additional1",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Телефон дополнительный №1",
            ),
        ),
        migrations.AlterField(
            model_name="user_basic_information",
            name="phone_additional2",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Телефон дополнительный №2",
            ),
        ),
    ]
