# Generated by Django 4.1 on 2023-01-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0003_alter_user_basic_information_email_home_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="сertificate_parts",
            options={
                "default_permissions": "",
                "ordering": ["pk"],
                "permissions": (
                    ("Сertificate_Parts_view", "Сертификаты части. Просмотр."),
                    ("Сertificate_Parts_change", "Сертификаты части. Редактирование."),
                    ("Сertificate_Parts_delete", "Сертификаты части. Удаление."),
                    ("Сertificate_Parts_add", "Сертификаты части. Добавить."),
                ),
                "verbose_name": "Сертификат части",
                "verbose_name_plural": "Сертификаты части",
            },
        ),
        migrations.AlterModelOptions(
            name="сertificates",
            options={
                "default_permissions": "",
                "ordering": ["pk"],
                "permissions": (
                    ("certificates_view", "Сертификаты. Просмотр."),
                    ("certificates_change", "Сертификаты. Редактирование."),
                    ("certificates_delete", "Сертификаты. Удаление."),
                    ("certificates_add", "Сертификаты. Добавить."),
                ),
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
            },
        ),
    ]
