# Generated by Django 4.1 on 2023-01-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0004_alter_сertificate_parts_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="сertificate_parts",
            options={
                "default_permissions": "",
                "ordering": ["pk"],
                "permissions": (
                    ("certificate_parts_view", "Сертификаты части. Просмотр."),
                    ("certificate_parts_change", "Сертификаты части. Редактирование."),
                    ("certificate_parts_delete", "Сертификаты части. Удаление."),
                    ("certificate_parts_add", "Сертификаты части. Добавить."),
                ),
                "verbose_name": "Сертификат части",
                "verbose_name_plural": "Сертификаты части",
            },
        ),
    ]
