# Generated by Django 4.1 on 2023-01-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0005_alter_сertificate_parts_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="сertificate_parts", name="years",),
        migrations.AddField(
            model_name="сertificate_parts",
            name="validity",
            field=models.IntegerField(default=0, verbose_name="Срок годности месяцев"),
        ),
    ]
